# Generated by Django 2.0.9 on 2018-11-07 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=60)),
                ('rut', models.CharField(max_length=15)),
                ('nacimiento', models.CharField(max_length=12)),
                ('region', models.CharField(max_length=50)),
                ('comuna', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('vivienda', models.CharField(max_length=20)),
            ],
        ),
    ]
