# Generated by Django 2.0.9 on 2018-11-08 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Luchador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.CharField(max_length=200)),
                ('nombre', models.CharField(max_length=100)),
                ('peleas', models.CharField(max_length=10)),
                ('biografia', models.CharField(max_length=300)),
                ('division', models.CharField(max_length=50)),
            ],
        ),
    ]
