# Generated by Django 2.0.9 on 2018-11-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0002_luchador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luchador',
            name='imagen',
            field=models.ImageField(upload_to=''),
        ),
    ]
