# Generated by Django 2.0.9 on 2018-11-10 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0004_auto_20181108_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luchador',
            name='imagen',
            field=models.ImageField(upload_to='inicio/static/subidas/'),
        ),
    ]
