# Generated by Django 2.0.9 on 2018-11-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0005_auto_20181109_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luchador',
            name='imagen',
            field=models.ImageField(upload_to='inicio/media/subidas/'),
        ),
    ]
