# Generated by Django 2.0.9 on 2018-11-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0006_auto_20181110_1103'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='contrasena',
            field=models.CharField(default=12345, max_length=30),
            preserve_default=False,
        ),
    ]
