# Generated by Django 2.0.9 on 2018-11-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0008_luchador_pertenece'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luchador',
            name='division',
            field=models.CharField(choices=[('asignar', 'Indique Seleccion'), ('pluma', 'Peso Pluma'), ('medio', 'Peso Medio'), ('pesado', 'Peso Pesado')], default='asignar', max_length=50),
        ),
    ]
