# Generated by Django 2.0.9 on 2018-11-10 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0010_auto_20181110_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='vivienda',
        ),
        migrations.AddField(
            model_name='persona',
            name='suscripcion',
            field=models.CharField(choices=[('normal', 'Normal'), ('sincomerciales', '5 Merciales'), ('ilimitado', 'Ilimitado'), ('premium', 'Premium')], default='normal', max_length=50),
        ),
    ]
