# Generated by Django 2.0.9 on 2018-11-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0012_auto_20181112_0005'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='usuario',
            field=models.CharField(choices=[('1', 'Registrado'), ('2', 'Administrador')], default='1', max_length=50),
        ),
    ]
