# Generated by Django 2.0.9 on 2018-11-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0014_auto_20181112_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='luchador',
            name='division',
        ),
        migrations.AddField(
            model_name='luchador',
            name='estado',
            field=models.CharField(choices=[('contendiente', 'Contendiente'), ('retador', 'Retador'), ('campeon', 'Campeon'), ('leyenda', 'Leyenda')], default='contendiente', max_length=50),
        ),
    ]
