# Generated by Django 2.0.9 on 2018-11-13 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0016_luchador_contador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='luchador',
            name='contador',
            field=models.CharField(default=0, max_length=15),
        ),
    ]
